### ISSUE TITLE
Entrati Bounty not showing correct rewards

### ISSUE THREAD

**Issue by GrimmOblivion** [WFCD/warframe-hub#483] opened 2021-03-31 23:07 UTC
Summary (short):
---
Th tracker showing wrong rewards for Entrati Bountys (15-25) and (25-30), they also appear to be switched.

Description:
---
Longer, more technical description if possible

Reproduction:
---
1. in game at Mother in Necralisk.
2. hub. warframestat .us open, with the Entrati Bounty Cycle set to "Always eeexpand rewards."
3. compared the two bounties.

Screenshots, evidence:
Capture 1 shows (15-25) rewards.
![Capture1](https://user-images.githubusercontent.com/35074521/113221938-d2f59380-923a-11eb-9297-c8542d157110.JPG)

Capture 2 shows (25-30) rewards.
![Capture2](https://user-images.githubusercontent.com/35074521/113221945-d6891a80-923a-11eb-9103-d7441e91e261.JPG)

Capture 3 shows hub. warframestat .us bounty rewards.
![Capture3](https://user-images.githubusercontent.com/35074521/113221951-d9840b00-923a-11eb-9e14-71671ed11947.JPG)

Capture 4 shows (100-100 Steel Path) rewards to show accuracy of the other bounties.
![Capture4](https://user-images.githubusercontent.com/35074521/113221952-db4dce80-923a-11eb-8438-1b273684a6b6.JPG)

---
Screenshot so it's easy for us to compare

**Comment by TobiTenno** [comment] 2021-05-08 18:10
all of them are matched by the string DE provides, which is the same across open worlds, so unless there's some other bits, I've go no way of knowing. This is also a duplicate of an existing issue that's over on warframe-worldstate-parser, as that's where this matching occurs.

closing as a duplicate of https://github.com/WFCD/warframe-worldstate-parser/issues/242

**Closed as completed by TobiTenno** 2021-05-08 18:10 UTC
Labels: Type: Bug, Severity4: Inconvenient, Scope: Documentation
