### ISSUE TITLE
Angels of The Zariman support

### ISSUE THREAD

**Issue by TheNormalestPeep** [WFCD/warframe-hub#1007] opened 2023-04-24 01:58 UTC
### What would you like to see happen?

Add support for the Zariman bounties, as well as Zariman cycles

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment] 2023-04-24 03:03
How would you propose we do so? Neither of the above exist in DE's worldstate, last I checked... (just now).

```json
[
  {
    "id": "1682305349744ZarimanSyndicate",
    "activation": "2023-04-24T00:32:30.870Z",
    "startString": "-2h 27m 13s",
    "expiry": "2023-04-24T03:02:29.744Z",
    "active": true,
    "syndicate": "The Holdfasts",
    "syndicateKey": "The Holdfasts",
    "nodes": [],
    "jobs": [],
    "eta": "2m 45s"
  },
  {
    "id": "1682314348619ZarimanSyndicate",
    "activation": "2023-04-24T03:02:29.745Z",
    "startString": "2m 45s",
    "expiry": "2023-04-24T05:32:28.619Z",
    "active": false,
    "syndicate": "The Holdfasts",
    "syndicateKey": "The Holdfasts",
    "nodes": [],
    "jobs": [],
    "eta": "2h 32m 44s"
  }
]
```
here's 2 entries for The Holdfasts. We have times for starting, but not times for when each faction is taking over (generally it's about in the middle of the bounty cycle); and no bounties, unfortunately.

**Comment by TobiTenno** [comment] 2023-04-24 03:04
dupe of #797

**Closed as not planned** 2023-04-24 03:04 UTC
Labels: Scope: Core, Type: Feature Request
